name: test-workflow
on: [push, pull_request]

jobs:
  test:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build
